### ISSUE TITLE
Make the "klay" keyword changable

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1236]
**Purpose**
Some service chains and other Klaytn networks want to use their own token name, but `klay` is the only possible native token name and API namespace in Klaytn. Let 's provide a configurable that can change the native token name and API namespace.

**TODO**

- [ ]  Investigate all places `klay` is exposed to users.
- [ ] Change a node configurable that can change `klay` to another keyword. Howerver, `klay` namespace needs to be allowed also.
- [ ] (Update Klaytn Docs about the features)

**Comment by kjhman21** [comment]
@aidan-kwon @aeharvlee Since it is not that high priority, what about leaving this as a backlog, not including v1.8.3?

**Comment by aidan-kwon** [comment]
Close this since we don't have enough users requiring this feature.
