### ISSUE TITLE
QA for v1.12.0

### ISSUE THREAD

**Issue by blukat29** [klaytn/klaytn#2043]
- Regular tests
	- [x] ok @JayChoi1736 @yoomee1313 https://github.com/klaytn/klaytn/issues/2043#issuecomment-1825037461 
- Cancun hardfork tests  
	- [x] EIP-2930 AccessList Tx @sjnam https://github.com/klaytn/klaytn/issues/2043#issuecomment-1826924236
	- [x] EIP-6780 SELFDESTRUCT
	- [x] EIP-5656 MCOPY @hyunsooda https://github.com/klaytn/klaytn/issues/2043#issuecomment-1826999578
	- [x] EIP-1153 TLOAD and TSTORE
	- [x] EIP-4844 BLOBHASH and KZG precompile 
	- [x] EIP-7516 BLOBBASEFEE
	- [x] EIP-1052 EXTCODEHASH fix
	- [x] ComputationCostCancun @yoomee1313 https://github.com/klaytn/klaytn/issues/2043#issuecomment-1831034292
- Randao hardfork tests
	- [x] KIP-149 System contracts registry @ian0371 https://github.com/klaytn/klaytn/issues/2043#issuecomment-1825382761
	- [x] KIP-113 BLS public key registry
	- [x] KIP-114 RANDAO @hyeonLewis https://github.com/klaytn/klaytn/issues/2043#issuecomment-1823742802
	- [x] KIP-146 Unpredictable proposer selection
- RPC changes
	- [x] fix `klay_sendRawTransaction` error message @hyunsooda https://github.com/klaytn/klaytn/issues/2043#issuecomment-1826999578
	- [x] fix `debug_traceTransaction` to EOA
	- [x] fix `klay_recoverFromTransaction` with Eth tx types
	- [x] fix `*get{Block,Header}*` with pending block number shall not panic in CN
	- [x] fix `eth_get{Block,Header}*` outputs nonzero mixHash if RandaoForkEnabled
	- [x] fix `klay_get{Block,Header}*` outputs nonzero mixHash and randomReveal if RandaoForkEnabled
	- [x] fix `eth_maxPriorityFeePerGas` returns zero
	- [x] fix `klay_forkStatus`
	- [x] new `*_getBlockReceipts`
	- [x] new `admin_nodeConfig`
	- [x] new `*_createAccessList`
- Governance and setHead changes
	- [x] `debug_setHead` can repair broken governance states @yoomee1313 https://github.com/klaytn/klaytn/issues/2043#issuecomment-1831029617
	- [x] `debug_setHead` early exits in certain circumstances
- Upstream EN
	- [x] Can fall-back missing trie node error @2dvorak https://github.com/klaytn/klaytn/issues/2043#issuecomment-1825059433
- JS console
	- [x] works and supports ES6 @2dvorak https://github.com/klaytn/klaytn/issues/2043#issuecomment-1825059433
- ~Live pruning~
	- [x] ~Can switch on/off @2dvorak https://github.com/klaytn/klaytn/issues/2043#issuecomment-1825059433~
- Consensus
	- [x] Works as intended @jiseongnoh https://github.com/klaytn/klaytn/issues/2043#issuecomment-1837959667
	- [x] Works in various consensus network sizes @ian0371 @jiseongnoh https://github.com/klaytn/klaytn/issues/2043#issuecomment-1825382761
	- [x] Safe to gradually upgrade CNs

**Comment by blukat29** [comment]
Cancun hardfork tests (4844, 7516, 1052)

- [ ] EIP-4844 KZG precompile
- [ ] EIP-4844 BLOBHASH opcode
- [ ] EIP-7516 BLOBBASEFEE opcode
- [ ] EIP-1052 EXTCODEHASH opcode
	- for empty account, returns 0xc5d2.. before fork, 0x0 after fork

<details>
<summary>Details</summary>

How to run
```sh
./homi setup --cn-num 1 --docker-image-id klaytn/klaytn:dev --cancun-compatible-blocknumber 60 --randao-compatible-blocknumber 999999
cd homi-output
docker compose up --force-recreate -d CN-0
docker compose cp test.js CN-0:/
docker compose exec CN-0 kcn attach --preload /test.js /klaytn/klay.ipc
> setup_all();
> check_eip1052(59);
> check_eip1052(60);
```

Script (test.js)
```js
async function sleep(msec) {
  return new Promise(r => setTimeout(r, msec));
}

async function pretty(obj) {
    console.log(JSON.stringify(obj, null, 2));
}

async function waitTx(txhash) {
  while (true) {
    var receipt = eth.getTransactionReceipt(txhash);
    if (receipt) {
      return receipt;
    }
    await sleep(1000);
  }
}

/*
// https://remix.ethereum.org/#lang=en&optimize=true&runs=200&version=soljson-v0.8.23+commit.f704f362.js
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.18;

contract C {
    function check() external view returns (bytes32) {
        address account = address(0x1234); // empty account
        bytes32 codehash;
        assembly { codehash := extcodehash(account) }
        return codehash;
    }
}
*/
var code_eip1052 = "0x608060405234801561000f575f80fd5b5060bb8061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c8063919840ad14602a575b5f80fd5b60306044565b604051603b9190606e565b60405180910390f35b5f8061123490505f813f9050809250505090565b5f81905091905056
var call_eip1052 = "0x919840ad";
var addr_eip1052 = "";

async function setup_eip1052() {
  var txid = eth.sendTransaction({ from: personal.listAccounts[0], to: null, data: code_eip1052 });
  console.log('== setup_eip1052 txid', txid);

  var receipt = await waitTx(txid);
  addr_eip1052 = receipt.contractAddress;
  console.log('== setup_eip1052 addr', addr_eip1052, 'at block', receipt.blockNumber);
}

function check_eip1052(num) {
  num = num || 'latest';
  var output = eth.call({ to: addr_eip1052, data: call_eip1052 }, num);
  console.log('== check_eip1052 call', output);
}

function setup_all() {
  setup_eip1052();
}
```

Result
```
> setup_all()
== setup_eip1052 txid 0xf63a4d8c49738fd2d3678391cd0951cf973cb79a2fc850793829ffecea706e92
== setup_eip1052 addr 0xce73f3598439a6b0c0df2abe10fe8042a6968ba3 at block 19

> check_eip1052(59)
  == check_eip1052 call 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470
> check_eip1052(60)
  == check_eip1052 call 0x0000000000000000000000000000000000000000000000000000000000000000
```

</details>

**Comment by hyeonLewis** [comment]
KIP-114 RANDAO & KIP-146 Unpredictable proposer selection

Testing process
* Environment
  * With 4 validators (all validators in committee) 
* KIP-114 & KIP-146
  * Gather N block headers.
  * Calculate `calcRandomReveal`, `calcMixHash`. (Proposer selection will be tested during `calcRandomReveal`)
  * Compare the calculated randao fields and actual header fields.

- [ ] RANDAO fields are correctly calculated by KIP-114
- [ ] Proposer is correctly calculated by KIP-146

**Comment by yoomee1313** [comment]
**Regular QA tests**
- [ ] RPC/WS test: 
 - 
- [ ] rolling update test:
 -
- [ ] governance test: 
 - 
- [ ] rosetta reward test: 
 - 
- [ ] sync test :

node | sync period | load | duration | result
-- | -- | -- | -- | --
baobab | 0 to 1,3903,5666 | very light | syncing |
cypress1 | 0 to 5000,0000 | very light | syncing |
cypress2 | 5000,0000 to 7500,0000 | light | syncing |
cypress3 | 7500,0000 to 8199,9872 | heavy | syncing |
cypress4 | 8199,9872 to 9000,0000 | heavy | syncing |
cypress5 | 9000,0000 to 1,0999,9104 | light | syncing |
cypress6 | 1,0999,9104 to 1,3864,1421 | light | syncing |

- [ ] load test - stress :
 - TC: transferSignedTx, newValueTransferTC, newFeeDelegatedSmartContractExecutionTC
 - TPS:
 - Peer Connection:
 - BlockGenerationTime: -
- [ ] load test - stability:
 - TC: transferSignedTx, newValueTransferTC, newFeeDelegatedSmartContractExecutionTC
 - TPS: 2000
 - Peer Connection: stable
 - BlockGenerationTime: -

**Comment by 2dvorak** [comment]
Maintenance
- [ ] Can fall-back to upstream EN for missing trie node
- [x] New JS console works and supports ES6
- [ ] Can switch on/off live pruning

<details>
<summary>Details</summary>

</details>

**Comment by ian0371** [comment]
- [ ] KIP-149 System contracts registry
  - [x] When randao fork = 0, `genesis.json` generated by `homi` contains 0x401 in `alloc`.
  - [x] When randao fork != 0, `genesis.json` does not.
- [ ] KIP-113 BLS public key registry
  - [-] `ken account bls-info`

`ken account bls-info` generates a new `nodekey` file when `nodekey` file is not found. This can be confusing when a node is running with `--nodekeyhex` flag.

**Comment by hyunsooda** [comment]
- RPC changes
	- [ ] fix `klay_sendRawTransaction` error message
	- [ ] fix `debug_traceTransaction` to EOA
	- [ ] fix `klay_recoverFromTransaction` with Eth tx types
	- [ ] fix `*get{Block,Header}*` with pending block number
	- [ ] fix `eth_maxPriorityFeePerGas` returns zero
	- [ ] fix `klay_forkStatus`
	- [ ] new `*_getBlockReceipts`
	- [ ] new `admin_nodeConfig`
	- [ ] new `*_createAccessList`

**Comment by yoomee1313** [comment]
setHead test
* debug_setHead can repair broken governance states
  * [x] call setHead on the block which is before voting period
  * [x] call setHead on the block which is in the middle of voting period
  * [x] call setHead on the block which is after governance block
  * [x] call setHead on the block which is after applying block
* [ ] debug_setHead early exits in certain circumstances (?)

<details>
<summary>Details</summary>
test steps
1. deploy private network (cn1,pn1,en1) with v1.11.1 binaries. set epoch as 30.
2. vote at block 15. governance block will be 30 and applying block will be 60.
3. wait until block 100.
4. call setHead(10): rewinding succeed
5. call setHead(20): bad block occurs
6. call setHead(40): rewinding succeed
7. call setHead(80): rewinding succeed
8. initialize private network and vote again in same block. wait until block 100.
9. call setHead(10): rewinding succeed
10. call setHead(20): rewinding succeed
11. call setHead(40): rewinding succeed
12. call setHead(80): rewinding succeed

**Comment by yoomee1313** [comment]
ComputationCostCancun Test
- [ ] recalculate computation cost of dfk transaction
- [ ] check computationcostlimit hardfork change is applied when hardfork activates

<details>
<summary>Details</summary>
test steps </br>
1. deploy a baobab archive en for test with experimental computationcostlimit setting flag
2. stop syncing to avoid bad block issue

test steps </br>
1. deploy private network and set cancun hardfork as 100
2. deploy a transaction which computation cost is 110 mil
3. check the transaction is failed before hardfork
4. wait until cancun hardfork activates
5. check the transaction is succeed after hardfork

**Comment by jiseongnoh** [comment]
Consensus test - when all nodes are patched to v1.12, they are making consensus without problems and the quorum size has changed as expected.

Node count: seven validator nodes

Test Procedure:
1) upgrade all nodes to version 1.12
2) run the validator nodes
3) change committee size and see the quorum changes

command to monitor the committed seal size:
```
  kcn --exec "console.log(JSON.stringify(klay.getHeaderByNumber('latest')))" attach http://localhost:8551 | head -1 > block.
 kcn util decode-extra block.json | jq .committedSealSize

```
