### ISSUE TITLE
QA for v1.12.1

### ISSUE THREAD

**Issue by blukat29** [klaytn/klaytn#2096]
- Regular tests
	- [x] baobab sync test @yoomee1313 
- Node fixes
	- [x] fix slow startup due to Istanbul snapshot ([#2064], [#2074]) https://github.com/klaytn/klaytn/issues/2096#issuecomment-1907199404(https://github.com/klaytn/klaytn/pull/2074)) @yoomee1313 
	- [x] fix block sync issue regarding Randao and missing trie node ([#2092](https://github.com/klaytn/klaytn/pull/2092))
	- [x] fix block download cancel issue ([#2100](https://github.com/klaytn/klaytn/pull/2100))
	- [x] fix unsafe debug APIs to be accessible via IPC, but not via RPC with `--rpc.unsafe-debug.disable` ([#2075](https://github.com/klaytn/klaytn/pull/2075)) @2dvorak 
	- [x] fix to run on old Intel chips and ARM Mac ([#2091](https://github.com/klaytn/klaytn/pull/2091))
- RPC changes
	- [x] new `eth_getProof` and `klay_getProof` ([#2068](https://github.com/klaytn/klaytn/pull/2068)) @2dvorak 
	- [x] update `klay_getBlockWithConsensusInfo` and `ken util decode-extra` to show round and committers ([#2088](https://github.com/klaytn/klaytn/pull/2088)) @jiseongnoh 
	- [x] update `debug_trace*` to show computation cost ([#2090](https://github.com/klaytn/klaytn/pull/2090)) @hyeonLewis 
	- [x] fix `debug_chaindbProperty` and `debug_chaindbCompact` ([#2062](https://github.com/klaytn/klaytn/pull/2062)) @hyunsooda 
	- [x] fix `klay_getBlockWithConsensusInfo` to work without receipts ([#2071](https://github.com/klaytn/klaytn/pull/2071))
	- [x] fix `klay_` transaction APIs to recognize `input` field ([#2085](https://github.com/klaytn/klaytn/pull/2085))
	- [x] fix call, estimate transaction APIs to ignore computation cost limit, but respect gas cap and timeout ([#2086](https://github.com/klaytn/klaytn/pull/2086))

**Comment by hyunsooda** [comment]
- [ ] fix `debug_chaindbProperty` and `debug_chaindbCompact` ([#2062](https://github.com/klaytn/klaytn/pull/2062)) 
- [ ] fix `klay_getBlockWithConsensusInfo` to work without receipts ([#2071](https://github.com/klaytn/klaytn/pull/2071))
- [ ] fix `klay_` transaction APIs to recognize `input` field ([#2085](https://github.com/klaytn/klaytn/pull/2085))
- [ ] fix call, estimate transaction APIs to ignore computation cost limit, but respect gas cap and timeout ([#2086](https://github.com/klaytn/klaytn/pull/2086))

**Comment by hyeonLewis** [comment]
update `debug_trace*` to show computation cost

* Environment
   * homi setup --cn-num 1 local --funding-addr ${your_testing_addr}
   
* Testing process
    1. Prepare a simple contract and transaction to check
    2. Call `debug_traceCall`, `debug_traceTransaction`, `debug_traceBlockByHash`
    3. Check the `computation` and `computationCost` fields are correctly returned by comparing with actual values

* Results
    - [x] `debug_traceCall`
    - [x] `debug_traceTransaction`
    - [x] `debug_traceBlockByHash`
    - [x] `debug_traceTransaction` and `debug_traceBlockByHash` have same returns for same tx
    <details>
    <summary>Test output</summary>

   ```
    totalCost:  45483 // debug_traceBlockByHash
    All computation costs are correct!

    totalCost:  45483 // debug_traceTransaction
    All computation costs are correct!

    totalCost:  22569 // debug_traceCall
    All computation costs are correct!

    Same result! // Compare traceBlockByHash and traceTransaction
   ```

    </details>
* Test code
    * All codes can be found here: https://github.com/hyeonLewis/qa-klaytn/tree/main/src/debug_cc

**Comment by 2dvorak** [comment]
- [ ] fix unsafe debug APIs to be accessible via IPC, but not via RPC with --rpc.unsafe-debug.disable (#2075)
- [ ] fix to run on old Intel chips and ARM Mac (#2091)
- [ ] new eth_getProof and klay_getProof (#2068)

<details>
<summary> details </summary>

- Test binary on old Intel chips and ARM Mac
   - Intel
   ```
   2dvorak@MacBook-Pro bin % sysctl -n machdep.cpu.brand_string
   Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
   2dvorak@MacBook-Pro bin % ./kcn version
   Klaytn v1.12.1~rc.1+95c5ae608b
   2dvorak@MacBook-Pro bin % ./homi --version
   homi version v0.3.3
   ```
   - Arm
   ```
   ```
</details>

**Comment by yoomee1313** [comment]
fix slow startup due to Istanbul snapshot

Test steps
- deploy cn1/pn1/en1 network. epoch is 30. en is full-en.
- vote ratio vote for testing data and give value transfer tx load.
- restart the network.

[ ] full-en node
- setHead(500) at 1500000 at en

Checks
- klay.getBalance(128*220):
- ...

[ ] state migrated node
- migrate the state
- setHead(500) at 1500000 at en

**Comment by jiseongnoh** [comment]
./ken --exec "console.log(JSON.stringify(klay.getHeaderByNumber('latest')))" attach https://public-en-cypress.klaytn.net | head -1 > block.json
 ./ken util decode-extra block.json
```
{
  "committedSeal": [
    "0x29414e943ad6533a8e73f128b8e1140f4632e392beb8908ef5563b426dedc64041f337baee101f6fe9b9d21855e49167fc7ca47992f4b314ecb1e0dcbbfd97ee01",
    "0xb7eec4beb0364ebeb36dca3f3fcee4d6cfad1b3ce06bcf5839e10b8414efc13b537f49f60d4a71f379e56bc13f47effe8b43dfe7d03816ac84dcb9fc9c7e738a00",
    "0x9b3227daec2802aa9f7a1b91144f371ce32f45a9d82f6133f83c3b7b8fa0c0b04cfbb60548b175fb92714046adb045e557ea083adfea8a9e82de1772221115e400",
    "0x9d6a4dfb9457d883639fb57fd3d4c90c3dd67d1f7001156e1a05da35b7f7e7950b911a1aed08b52e6a7c8e813903aabbe3527eb58b63685c6c3c0d9ebfe0d0e501",
    "0x87ccb633c4599a379a67ef26b615390c340eb27882dcfe322d13ed89c48c85c314637eb2e50b47c6dff60b6016dc77dd277bd3f81c8130c9eb2f416cb08b93d801",
    "0xb05df995eb8900c9cc7730ba1dbc8cbd224988b01d6d4d4dfcfd7869a02c72714dea4da64e4dc91875d6bfeb7d15c439c1f5f4f51d94b6aed4dbb3632061223201",
    "0x87c0e079dc3db3ef04eeae6f72947c13b4c113ae18996574ec03a4aa2f7aeae8771e1a8ac41b4d8033414b56226167c7a988b3a23f37113681df01e1644d9f5f00",
    "0x93a93394e18561a0f777e69379e911bcb10ae4b8493439500b4dfaadd79fa6544371bd4a42a13bbfb5c21098e676c574172ab73113c6704e5a106ae17ade541f00",
    "0x7dddec5eb9e86bb18545008a2719136c215523bea3f235804dae8b093e20fa1317b689228338cc21bf902a7016a6528de044f2e9dc19b07ea6934eaf0f7bdacb01",
    "0x71c4f88e61d5679b94a768fa6c9b3524845292c60684201da1de31c8dcdd13506a690a36a5a1337fede6a496977eac31d2fd2de48892d8ef0e1f4fa9478b01c001",
    "0xe74ff116ad87564c43281f7f8a1368465ae88cee7bb210057c8f280b91e30f3a71a1eb0b1a951ef5e9d0b2337a51368019d603f2829141d49e1e1d942be0245701",
    "0x8825b05e62f21640202910fb899fbe41c4acbff569d35b6903f29265fac1df2833ea3cd1d02df36b78320b38adbe23e548655b0ba9f3cc10408589c9932444e800",
    "0x3162d556ce201832b66c7a6f2bbc4c3ef2e57c743796a91ead94353a4e5f35fb46d2fc8e45990a979ca2a919861ccf05d58ec9c2e93cfb0de2952f75cd3a9c6a00",
    "0x3fcfa2d6058bef5326533cf53cb4a1bb3936876cfd1be04c96067b9774cb31a45fac3317086f175add807ccec0ba9fd515667bbf46c067191c0582c2b2cdb31d00",
    "0xad9575f55ef029702c8684637c737ad0aaa13fce2feb081f338bc1bb1344cb5b447ec23cb3ab7a0229278e61b4751eb709d4845444d24e51d64d8a8c5f0cd0c500",
    "0xbfb9ca51c52663020f9b274959f52cb7aa01987add7227907a1e3d56b3bf2df6449e9db6f4a8d747f622d2196b72c5e529e6945955ba819369b37088be3c95a301",
    "0x12b9234f9eb7b6be0cc8a1f40bbde249ff95048e8c4634f9ac14843b701151523ad4d3e8cbb5df475ba7686a9297a122e0cdcb0ebd184dd10c58f94dafd7857700",
    "0x068db5f0668e68f75ce1fe14bd76b1074405e0832d0358fc1176859a9a677aa16eb46b890680c799967657ee1994faf12e9dbdc00e941b3255885aa083bfb2d801",
    "0x2af79606d50564c41ecfd364ef8ae74f7ec7a3f040ccaad78a9ee266d59c7f4a24a8651ef1711f42b6af06515e17476ba1dfa142b6742eb16eb9bc09714b0acd01",
    "0xdb3a6807e45f2f1de505b184658b2f8e3fecb9c7198a79cad5db7398be9468235bc3f8b1e7824908d907487294a6c85a1918900d051d0c6b5d49fc6fd3ceafb901",
    "0xba1d1e32c5b5bdd25f2f5fa6c3d69d332ae872ed36383f479cc028f748b75ff00cab9a6cbe144c4828da68cda5f0811aef0063ae15e0c85c1d0d945336ef736400"
  ],
  "committedSealSize": 21,
  "committers": [
    "0xf8c9c61c5e7f2b6219d1c28b94e5cb3cdc802594",
    "0x36ff2aa21d5c6828ee12cd2bc3de0e987bc0d4e7",
    "0x4b9f98831da1af95f96a1ad3d78ad8a125dbb452",
    "0x52d41ca72af615a1ac3301b0a93efa222ecc7541",
    "0xed6ee8a1877f9582858dbe2509abb0ac33e5f24e",
    "0x914d442497480dd1a73dc0768f33549ba52a9c2e",
    "0x386ca3cb8bb13f48d1a6adc1fb8df09e7bb7f9c8",
    "0x53970bc504cbc41c2a0e6460aef7d86655186284",
    "0xe93a890fb7ec5e993b1a7fd77b0d13a0763eff3d",
    "0xdf6571ab9f25eb365c65ff9ee915298580681b82",
    "0xe85d197a80d60564616983f5d2a112b97f61a0ff",
    "0x7b065fbb3a9b6e97f2ba788d63700bd4b8b408bc",
    "0x74f64cb6c2db9e0b270df1d4e563920381aec034",
    "0xbc28b81e73a66747695d9236dc20491d65f74381",
    "0x8d53a7dd56464ec4ba900cef1e7eab041ba61fc1",
    "0x52c0f3654e9ac47ba5e64ffcb398be485718a74b",
    "0xec6c1cede510be308f0fdbbc8dbdf238829bdb34",
    "0x56e3a565e31f8fb0ba0b12c03355518c64372120",
    "0xc0cbe1c770fbce1eb7786bfba1ac2115d5c0a456",
    "0x03497f51c31fe8b402df0bde90fd5a85f87aa943",
    "0xbca8ffa45cc8e30bbc0522cdf1a1e0ebf540dfe2"
  ],
  "hash": "0xc0a1f88a5c72bffd2c541029f6b49e29773815bf4f58cf6289ec120d088dc46b",
  "proposer": "0xBc28b81E73a66747695D9236dC20491D65f74381",
  "round": 0,
  "seal": "0x7e1e923a9ddc2a6b4b78541287384b16bb70784d1b45b2c86080089b3a0d53d6512a5bd3702f1dcb8d7fab619383ad634bafefaceab707ad79b2ae47f51e965500",
  "validatorSize": 32,
  "validators": [
    "0x03497F51c31fE8b402DF0bDE90Fd5A85f87aA943",
    "0x0b59caE1F03534209FdB9dDF5eA65b310Cd7060c",
    "0x1390eAb3AD2e674646A8F92460098886409FD57B",
    "0x20685d7bBcb07DDdBd8dbDC824C31fe2bfB31c92",
    "0x21eea769292304D12e378Ddb098f762A248eEff3",
    "0x36Ff2Aa21d5c6828EE12CD2bc3DE0E987bC0d4E7",
    "0x386Ca3Cb8bB13f48D1a6adC1fb8df09e7Bb7f9c8",
    "0x4B9f98831da1AF95f96A1Ad3D78AD8a125DbB452",
    "0x4c921E2B4ac183B9b8ab32805eF4dA8D59D49eAE",
    "0x52c0F3654E9Ac47ba5e64FfcB398bE485718a74B",
    "0x52d41cA72aF615a1ac3301b0A93EFA222EcC7541",
    "0x53970bC504cbC41c2a0e6460AeF7D86655186284",
    "0x56e3a565E31F8fb0bA0b12C03355518C64372120",
    "0x6873352021FE9226884616dC6F189f289AEb0cC5",
    "0x74f64cb6c2dB9e0b270dF1D4E563920381AeC034",
    "0x7B065fBb3A9B6e97F2ba788d63700bD4B8B408Bc",
    "0x8D53A7dD56464EC4Ba900Cef1e7eab041Ba61FC1",
    "0x914D442497480dD1a73Dc0768F33549BA52a9c2e",
    "0xa3b387b7B0dC914a4F106Ad645A0Ad079d70EBdC",
    "0xBc28b81E73a66747695D9236dC20491D65f74381",
    "0xBCA8fFa45CC8e30bBC0522CdF1A1e0eBF540dfE2",
    "0xC0cBE1C770fbCE1eb7786BFBa1Ac2115D5C0a456",
    "0xc180cA565B34b5b63877674f5fE647E7dA079022",
    "0xd6D7762DD7FadF0512D83D0143685fC85488B64E",
    "0xDf6571ab9f25eb365C65FF9EE915298580681b82",
    "0xE36eA146C05757A38eC1493eEA8c878677A9c19a",
    "0xe3d92072D8b9A59a0427485A1b5f459271Df457C",
    "0xE85d197a80D60564616983f5d2a112b97F61A0fF",
    "0xE93A890fB7EC5E993b1A7FD77B0D13A0763Eff3D",
    "0xec6C1CEDE510Be308f0FDBbc8dBdF238829BDB34",
    "0xED6Ee8a1877f9582858dBE2509aBB0aC33E5f24E",
    "0xf8C9C61c5E7f2B6219D1C28B94E5cB3cDC802594"
  ]
}
```

**Comment by yoomee1313** [comment]
Sync test

Conducted only the baobab sync test for this release

node | sync period | load | duration
-- | -- | -- | --
baobab1 | 0 to 120,000,000 | very light | 
baobab2 | 120,000,000 to 144,529,711 | light |
